# Funding information for the project
# Users can support development through these platforms

github: [juan-dev]  # Replace with actual GitHub username
custom: ['https://www.buymeacoffee.com/juandev']  # Replace with actual link
