"""
Barchart Component Adapter for py_cui.

Adapter that converts Barchart component to py_cui TextBlock widget
with ASCII bar charts generated by plotext.

Author: Dev Sênior Rafael
Date: 2025-11-11
Sprint: 4 (Bar Charts)
"""

from typing import Any, Dict, List, Tuple
import py_cui
import plotext as plt
import io
import sys

from src.adapters.component_adapter import ComponentAdapter
from src.utils.ansi_stripper import strip_ansi_codes


# Color mapping: component color name → py_cui color code
COLOR_MAP = {
    'green': py_cui.GREEN_ON_BLACK,
    'yellow': py_cui.YELLOW_ON_BLACK,
    'red': py_cui.RED_ON_BLACK,
    'cyan': py_cui.CYAN_ON_BLACK,
    'blue': py_cui.BLUE_ON_BLACK,
    'magenta': py_cui.MAGENTA_ON_BLACK,
    'white': py_cui.WHITE_ON_BLACK,
}


class BarchartAdapter(ComponentAdapter):
    """
    Adapter for Barchart component → py_cui TextBlock with plotext bar charts.

    Generates ASCII bar charts for categorical data using plotext library.
    Supports horizontal and vertical orientations.

    Example:
        >>> from src.components.barchart import Barchart
        >>> component = Barchart(config)
        >>> adapter = BarchartAdapter(component)
        >>> widget = adapter.create_widget(pycui_root, row=0, col=0, row_span=15, col_span=60)
        >>> adapter.update_widget({'network': {'protocol_distribution': {'TCP': 60, 'UDP': 30, 'ICMP': 10}}})
    """

    def __init__(self, component: Any):
        """
        Initialize adapter.

        Args:
            component: Barchart component instance
        """
        super().__init__(component)

        # Extract Barchart-specific config
        self.orientation: str = component.config.extra.get('orientation', 'horizontal')
        self.max_bars: int = component.config.extra.get('max_bars', 10)
        self.max_label_length: int = component.config.extra.get('max_label_length', 30)

    def create_widget(
        self,
        pycui_root: py_cui.PyCUI,
        row: int,
        col: int,
        row_span: int,
        col_span: int
    ) -> Any:
        """
        Create py_cui TextBlock for barchart display.

        Args:
            pycui_root: PyCUI root instance
            row: Starting grid row
            col: Starting grid column
            row_span: Number of rows to span
            col_span: Number of columns to span

        Returns:
            py_cui TextBlock widget
        """
        # Create TextBlock widget
        widget = pycui_root.add_text_block(
            title=self.component.config.title,
            row=row,
            column=col,
            row_span=row_span,
            column_span=col_span
        )

        # Set initial color if specified
        if self.component.config.color in COLOR_MAP:
            widget.set_color(COLOR_MAP[self.component.config.color])

        # Store widget reference
        self.widget = widget

        return widget

    def update_widget(self, plugin_data: dict) -> None:
        """
        Update widget with new plugin data.

        Extracts categorical data and generates bar chart with plotext.

        Args:
            plugin_data: Dictionary of plugin data
                {
                    'plugin_name': {
                        'field': {
                            'category1': value1,
                            'category2': value2,
                            ...
                        }
                    },
                    ...
                }
        """
        if not self.widget:
            return

        # Extract data from plugin
        plugin_name = self.component.config.plugin
        data_field = self.component.config.data_field

        if plugin_name not in plugin_data:
            self.widget.set_text("N/A - Plugin not available")
            return

        plugin_vals = plugin_data[plugin_name]

        if data_field not in plugin_vals:
            self.widget.set_text(f"N/A - Field '{data_field}' not found")
            return

        data = plugin_vals[data_field]

        # Parse data (dict or list of tuples)
        categories, values = self._parse_data(data)

        if not categories:
            self.widget.set_text("No data available")
            return

        # Generate chart
        chart = self._generate_chart(categories, values)

        # Update widget
        self.widget.set_text(chart)

    def _parse_data(self, data: Any) -> Tuple[List[str], List[float]]:
        """
        Parse data into categories and values.

        Args:
            data: Dict {'label': value} or List [(label, value), ...]

        Returns:
            Tuple of (categories, values)
        """
        categories = []
        values = []

        # Dict format
        if isinstance(data, dict):
            items = list(data.items())
        # List of tuples format
        elif isinstance(data, list):
            items = data
        else:
            return ([], [])

        # Sort by value (descending) and limit to max_bars
        items_sorted = sorted(items, key=lambda x: x[1], reverse=True)[:self.max_bars]

        for label, value in items_sorted:
            # Truncate long labels
            if len(label) > self.max_label_length:
                label = label[:self.max_label_length - 3] + "..."

            categories.append(label)

            # Convert to float
            try:
                values.append(float(value))
            except (ValueError, TypeError):
                values.append(0.0)

        return (categories, values)

    def _generate_chart(self, categories: List[str], values: List[float]) -> str:
        """
        Generate ASCII bar chart using plotext.

        Args:
            categories: List of category labels
            values: List of numeric values

        Returns:
            ASCII chart as string
        """
        if not categories or not values:
            return "No data to display"

        # Clear previous plot
        plt.clf()

        # Create bar chart (horizontal by default)
        if self.orientation == "vertical":
            plt.bar(categories, values, orientation="vertical")
        else:
            plt.bar(categories, values, orientation="horizontal")

        plt.title(self.component.config.title)

        # Set axis limits to avoid division by zero with similar values
        if values:
            min_val = min(values)
            max_val = max(values)
            value_range = max_val - min_val

            if value_range < 0.01:  # Values too close - use fixed margin
                margin = max(abs(max_val) * 0.1, 0.1)  # 10% of value or 0.1 minimum
            else:
                margin = value_range * 0.1  # 10% margin

            if self.orientation == "vertical":
                plt.ylim(min_val - margin if min_val - margin > 0 else 0, max_val + margin)
            else:
                plt.xlim(min_val - margin if min_val - margin > 0 else 0, max_val + margin)

        # Capture output to string
        output = io.StringIO()
        old_stdout = sys.stdout
        sys.stdout = output

        try:
            plt.show()
        finally:
            sys.stdout = old_stdout

        chart_text = output.getvalue()

        # CRITICAL FIX: Strip ANSI codes for py_cui compatibility
        # py_cui uses curses which does NOT interpret ANSI escape sequences
        # Without this, chart appears as garbage: ^[[48;5;15m instead of colors
        clean_chart = strip_ansi_codes(chart_text)

        return clean_chart

    def __repr__(self) -> str:
        """String representation for debugging."""
        return (
            f"BarchartAdapter("
            f"component={self.component.config.title}, "
            f"orientation={self.orientation}, "
            f"max_bars={self.max_bars})"
        )
